---
title: "Predict Life Expectancy"
author: "Michael Vaden"
date: "2024-06-02"
output: html_document
---

```{r}
library(tidyverse)
library(tidymodels)
```

```{r}
X1 <- read.csv("/Users/michaelvaden/Downloads/2020_Raw_Indicators_HOI_LE.csv")
indicators_2015 <- read.csv("/Users/michaelvaden/Downloads/indicators_used_for_LE/indicators_2015.csv")
indicators_2016 <- read.csv("/Users/michaelvaden/Downloads/indicators_used_for_LE/indicators_2016.csv")
indicators_2017 <- read.csv("/Users/michaelvaden/Downloads/indicators_used_for_LE/indicators_2017.csv")
indicators_2018 <- read.csv("/Users/michaelvaden/Downloads/indicators_used_for_LE/indicators_2018.csv")
indicators_2019 <- read.csv("/Users/michaelvaden/Downloads/indicators_used_for_LE/indicators_2019.csv")
indicators_2021 <- read.csv("/Users/michaelvaden/Downloads/indicators_used_for_LE/indicators_2021.csv")
```

```{r}
predict_life_expectancy <- function(new_data) {
  return ((new_data$Walkability * 0.097 ) + 
  (new_data$Environmental * 0.096) + 
  (new_data$`Food.Access` * 0.041) +
  (new_data$`Employment.Access` * 0.015) +
  (new_data$`Labor.Force.Participation` * 0.060) +
  (new_data$`Income.Inequality` * 0.002) + 
  (new_data$Incarceration * 0.347) +
  (new_data$Education * 0.160) +
  (new_data$`Spatial.Segregation` * 0.050) +
  (new_data$`Accees.to.Care` * 0.000) +
  (new_data$Townsend * 0.101) + 
  (new_data$Mobility * 0.030) + 
  (new_data$Affordability * 0.001) + 
  (new_data$`Population.Density` * 0.000))
  
}
```

```{r}
LE_predicted_2015 <- predict_life_expectancy(indicators_2015)*100

cor(X1$LifeExpectancy, LE_predicted_2015)

LE_data_2015 = indicators_2015 %>% select(geoid) %>% mutate(year = 2015) %>% mutate(measure = "life_expectancy_at_birth") %>% mutate(value = LE_predicted_2015) %>% mutate(moe = NA)

setwd("life_expectancy_predicted")
write.csv(LE_predicted_2015, "life_expectancy_2015.csv")
setwd("/Users/michaelvaden/Downloads")

cor(LE_predicted_2015, HOI_predicted_2015)
```

```{r}
LE_predicted_2016 <- predict_life_expectancy(indicators_2016)*100

cor(X1$LifeExpectancy, LE_predicted_2016)

LE_data_2016 = indicators_2016 %>% select(geoid) %>% mutate(year = 2016) %>% mutate(measure = "life_expectancy_at_birth") %>% mutate(value = LE_predicted_2016) %>% mutate(moe = NA)

setwd("life_expectancy_predicted")
write.csv(LE_predicted_2016, "life_expectancy_2016.csv")
setwd("/Users/michaelvaden/Downloads")

cor(LE_predicted_2016, HOI_predicted_2016)
```

```{r}
LE_predicted_2017 <- predict_life_expectancy(indicators_2017)*100

cor(X1$LifeExpectancy, LE_predicted_2017)

LE_data_2017 = indicators_2017 %>% select(geoid) %>% mutate(year = 2017) %>% mutate(measure = "life_expectancy_at_birth") %>% mutate(value = LE_predicted_2017) %>% mutate(moe = NA)

setwd("life_expectancy_predicted")
write.csv(LE_predicted_2017, "life_expectancy_2017.csv")
setwd("/Users/michaelvaden/Downloads")

cor(LE_predicted_2017, HOI_predicted_2017)
```

```{r}
LE_predicted_2018 <- predict_life_expectancy(indicators_2018)*100

cor(X1$LifeExpectancy, LE_predicted_2018)

LE_data_2018 = indicators_2018 %>% select(geoid) %>% mutate(year = 2018) %>% mutate(measure = "life_expectancy_at_birth") %>% mutate(value = LE_predicted_2018) %>% mutate(moe = NA)

setwd("life_expectancy_predicted")
write.csv(LE_predicted_2018, "life_expectancy_2018.csv")
setwd("/Users/michaelvaden/Downloads")

cor(LE_predicted_2018, HOI_predicted_2018)
```

```{r}
LE_predicted_2019 <- predict_life_expectancy(indicators_2019)*100

cor(X1$LifeExpectancy, LE_predicted_2019)

LE_data_2019 = indicators_2019 %>% select(geoid) %>% mutate(year = 2019) %>% mutate(measure = "life_expectancy_at_birth") %>% mutate(value = LE_predicted_2019) %>% mutate(moe = NA)

setwd("life_expectancy_predicted")
write.csv(LE_predicted_2019, "life_expectancy_2019.csv")
setwd("/Users/michaelvaden/Downloads")

cor(LE_predicted_2019, HOI_predicted_2019)
```

```{r}
LE_predicted_2021 <- predict_life_expectancy(indicators_2021)*100

cor(X1$LifeExpectancy, LE_predicted_2021)

LE_data_2021 = indicators_2021 %>% select(geoid) %>% mutate(year = 2021) %>% mutate(measure = "life_expectancy_at_birth") %>% mutate(value = LE_predicted_2021) %>% mutate(moe = NA)

setwd("life_expectancy_predicted")
write.csv(LE_predicted_2021, "life_expectancy_2021.csv")
setwd("/Users/michaelvaden/Downloads")

cor(LE_predicted_2021, HOI_predicted_2021)
```
