name: population_density
description: "Population density (persons per sq mile) from ACS + TIGER land area"

source:
  type: census_acs
  profile: VA_NCR
  years: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
  geographies: [tract, county, block_group]
  variables:
    total_pop: "B01001_001"

tiger:
  state_fips: "51"
  tract_layer: 8
  block_group_layer: 10
  county_layer: 86

output:
  path: data/distribution
  filename: population_density.csv.xz
  standardize: true

prepare:
  crosswalk: ../../geographies/VA/State Geographies/Health Districts/2020/data/distribution/va_ct_to_hd_crosswalk.csv
  source_col: ct_geoid
  target_col: hd_geoid
  method: mean
