name: gender_demographics
description: "Gender distribution from ACS"

source:
  type: census_acs
  profile: VA_NCR
  years: [2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
  geographies: [tract, county, block_group]
  variables:
    total_pop: "B01001_001"
    male: "B01001_002"
    female: "B01001_026"

output:
  path: data/distribution
  filename: gender_demographics.csv.xz
