---
title: "Poverty Data"
author: "Kathryn Linehan"
date: "2023-08-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(readr)
library(dplyr)
library(tidyr)
library(sf)
library(tmap)
library(RColorBrewer)
```

```{r}
# read in data and filter to FFX

adult_df <- read_csv("../data/distribution/ncr_tr_acs_2021_poverty_adults.csv.xz", 
                     col_types = "cncnn") %>%
  filter(substr(geoid, start = 1, stop = 5) == "51059")
```

```{r}
# parse measure column

categories = strsplit(adult_df$measure, split = "_")

adult_df$race = ""
adult_df$sex = ""
adult_df$type = ""

for(i in 1:length(categories))
{
  v = categories[[i]]
  
  if("pov" %in% v)  # poverty measures
  {
    if(length(v) == 4)
    {
      adult_df$race[i] = v[1]
      adult_df$sex[i] = v[2]
      adult_df$type[i] = paste(v[3], v[4], sep = "_")
    }
    else  # length is 5 -> wht_nonhis 
    {
      adult_df$race[i] = paste(v[1], v[2], sep = "_")
      adult_df$sex[i] = v[3]
      adult_df$type[i] = paste(v[4], v[5], sep = "_")
    }
  }
  else  # total counts
  {
    if(length(v) == 3)
    {
      adult_df$race[i] = v[1]
      adult_df$sex[i] = v[2]
      adult_df$type[i] = v[3]
    }
    else  # length is 4 -> wht_nonhis 
    {
      adult_df$race[i] = paste(v[1], v[2], sep = "_")
      adult_df$sex[i] = v[3]
      adult_df$type[i] = v[4]
    }
  }
}

```

```{r}

adult_df[adult_df$race == 'wht', "race"] <- "White"
adult_df[adult_df$race == 'blk', "race"] <- "Black"
adult_df[adult_df$race == 'his', "race"] <- "Hispanic (All Races)"
adult_df[adult_df$race == 'othr', "race"] <- "Other"
adult_df[adult_df$race == 'asian', "race"] <- "Asian"
adult_df[adult_df$race == 'wht_nonhis', "race"] <- "White (Non-Hispanic)"

```



```{r fig.width = 8, fig.height= 4}
# plot for poverty counts

df <- adult_df %>%
  filter(type == "pov_cnt")

df %>% filter(race != "White (Non-Hispanic)") %>%
ggplot(aes(x=race, y=value, fill=sex)) +
  geom_boxplot() +
  labs(title="Count of Adults in Poverty by Race and Ethnicity", 
       caption = "Data Source: American Community Survey \nAdults (18 and older), Fairfax County, Virginia, Census tracts, 2021",
       x="Race and Ethnicity", y="Count", fill="Sex") +
  scale_x_discrete(labels = c("Hispanic (All Races)" = "Hispanic"),
                   limits = c("Asian", "Black", "Other", "White", "Hispanic (All Races)")) +  
  theme_minimal() +
  theme(text = element_text(size = 16), legend.position = "bottom") +
  scale_fill_manual(values=c("#70ad48", "#4472c4"), labels = c("Female", "Male")) 

#ggsave("../docs/figures/poverty_counts.png")

```

```{r, fig.width = 6, fig.height= 4}
# plot for poverty percents

df <- adult_df %>%
  filter(type == "pov_pct")
  
df %>% filter(race != "White (Non-Hispanic)") %>%
ggplot(aes(x=race, y=value, fill=sex)) +
  geom_boxplot() +
  labs(title="Percent of Adults in Poverty by Race and Ethnicity", 
       caption = "Data Source: American Community Survey \nAdults (18 and older), Fairfax County, Virginia, Census tracts, 2021",
       x="Race and Ethnicity", y="Percent", fill="Sex") +
  scale_x_discrete(labels=c("Hispanic (All Races)"="Hispanic"),
                   limits = c("Asian", "Black", "Other", "White", "Hispanic (All Races)")) + 
  theme(text = element_text(size = 14)) +
  theme(legend.position = c(0.9, 0.8)) +
  theme_minimal() +
  theme(text = element_text(size = 14), legend.position = "bottom") +
  scale_fill_manual(values=c("#70ad48", "#4472c4"), labels = c("Female", "Male")) 

#ggsave("../docs/figures/poverty_percents.png")
```
```{r}

# poverty counts and percents by male/female (no race) for the entire county

pov_df <- adult_df %>%
  filter(type == "pov_cnt") %>%
  group_by(sex) %>%
  summarise(cnt = sum(value))

total_df <- adult_df %>%
  filter(type == "cnt") %>%
  group_by(sex) %>%
  summarise(cnt = sum(value))
  
100*pov_df$cnt[1]/total_df$cnt[1]
100*pov_df$cnt[2]/total_df$cnt[2]
 
```

```{r}

# find the 5 census tracts where each the count discrepancy is largest 

df <- adult_df %>%
  filter(type == "pov_cnt") %>%
  group_by(geoid, race) %>%
  mutate(diff_w_m = value[sex == 'women'] - value[sex == 'men'])

df_u <- unique(df[ , c("geoid", "year", "race", "diff_w_m")])

# get 5 lowest values per group - where women are not faring well

res <- df_u %>%
  arrange(desc(diff_w_m)) %>%
  group_by(race) %>%
  slice(1:5)

res$geoid <- as.character(res$geoid)
res$geoid <- substr(res$geoid,6,11)

```

```{r}
# plot

#race_labels = c("asian" = "Asian", "blk" = "Black", "his" = "Hispanic", "othr" = "Other", 
#                "wht" = "White", "wht_nonhis" = "White, non-Hispanic")

ggplot(res, aes(x=geoid, y=diff_w_m)) +
  geom_bar(stat = 'identity', fill = "navy") +
  facet_wrap(~race, nrow=2, scales = 'free_x') + #labeller = labeller(race = race_labels)) + 
  labs(title="Poverty Count Difference (Women-Men) by Race/Ethnicity (18+)", 
      x="Census Tract", y="Count Difference") +
  theme(axis.text.x = element_text(angle = 30)) +
  theme(text = element_text(size = 12))

#ggsave("../docs/figures/poverty_differences.png")
```


```{r}
# maps by census tract for poverty count difference

# get geometry

ffx_geo <- sf::st_read("https://raw.githubusercontent.com/uva-bi-sdad/sdc.geographies/main/VA/Census%20Geographies/Tract/2020/data/distribution/va_geo_census_cb_2020_census_tracts.geojson") %>%
  filter(substr(geoid,1,5) == "51059")

ffx_geo$centroid <- st_centroid(st_geometry(ffx_geo))


df_maps <- st_as_sf(merge(df_u, ffx_geo[ ,c("geoid", "geometry", "centroid")], by="geoid", all.x = TRUE))


```

```{r}
df_maps %>% 
  filter(race == "White") %>%
  ggplot() +
  geom_sf(aes(fill = diff_w_m)) + # fill = name of column with values to map
  labs(fill = "Difference", # Legend title
       title = "Poverty Count Difference (Women-Men) - 2021",  # Graph title
       subtitle = "White" ) + 
       #caption = "A great phrase explaining my figure \n
       #Data Source: American Community Survey, 5-Year Estimates, Table S1702") + 
        #Graph caption
  theme_void() # Takes out x and y axis, axis labels

```


```{r}
tmap_mode("plot")  # static view - not interactive

tm_shape(df_maps) +
    tm_polygons(col = "diff_w_m", 
                palette = "RdYlBu", 
                title = 'Difference',
                style = 'cont', 
                breaks = c(-100, -50, 0, 50, 100),
                labels = c("-100 and below", "-50", "0", "50", "100 and above")) +
  
    tm_facets(by = "race") +
    tm_layout(main.title = "Poverty Count Difference (Women-Men) - 2021")

#tmap_save(filename="../docs/figures/difference_map.png", asp=0.75)

```

```{r}

# find the 5 census tracts where each the percent discrepancy is largest 

df <- adult_df %>%
  filter(type == "pov_pct") %>%
  group_by(geoid, race) %>%
  mutate(diff_w_m_pct = value[sex == 'women'] - value[sex == 'men'])

df_u <- unique(df[ , c("geoid", "year", "race", "diff_w_m_pct")])

# get 5 lowest values per group - where women are not faring well

res <- df_u %>%
  arrange(desc(diff_w_m_pct)) %>%
  group_by(race) %>%
  slice(1:5)

```

```{r}
df_maps <- st_as_sf(merge(df_u, ffx_geo[ ,c("geoid", "geometry", "centroid")], by="geoid", all.x = TRUE))
```


```{r}
tmap_mode("plot")  # static view - not interactive

tm_shape(df_maps) +
    tm_polygons(col = "diff_w_m_pct", 
                palette = "RdYlBu", 
                title = 'Difference',
                style = 'cont') +
    tm_facets(by = "race") +
    tm_layout(main.title = "Poverty Percent Difference (Women-Men) - 2021")
```
```{r}
#Or just plot counts and percents of women in poverty?

w_df <- adult_df %>%
  filter(sex == "women" & type == "pov_cnt")  

w_df_maps <- st_as_sf(merge(w_df, ffx_geo[ ,c("geoid", "geometry")], by="geoid", all.x = TRUE))

```

```{r}
tmap_mode("plot")  # static view - not interactive

tm_shape(w_df_maps) +
    tm_polygons(col = "value", 
                palette = "YlOrBr", 
                title = 'Count',
                style = 'cont',
                breaks = c(0, 100, 200, 300),
                labels = c("0","100", "200", "300 and above")) +
    tm_facets(by = "race") +
    tm_layout(main.title = "Poverty Count (Women) - 2021")

#tmap_save(filename="../docs/figures/women_count_map.png", asp=0.75)
```

```{r fig.height = 10, fig.width = 14}
#Or just plot counts and percents of women in poverty?

w_df <- adult_df %>%
  filter(sex == "women" & (type == "pov_cnt" | type == "pov_pct"))  

w_df$measure <- NULL
w_df <- w_df %>% 
  pivot_wider(names_from = type, values_from = value)

w_df_maps <- st_as_sf(merge(w_df, ffx_geo[ ,c("geoid", "geometry", "centroid")], by="geoid", all.x = TRUE)) %>% filter(race != "White (Non-Hispanic)") %>% mutate(race = ifelse(race == "Hispanic (All Races)", "Hispanic", race))

w_df_maps %>% mutate(highlight = ifelse(pov_pct >= 30.55556, "yes", "no")) %>%
ggplot() +
  facet_wrap(vars(race))+#, labeller = labeller(race = race.labs)) +
  geom_sf(aes(fill = pov_pct, color = highlight), lwd = 1) + # fill = name of column with values to map
  coord_sf(crs = st_crs(4269)) + 
  labs(#fill = ,
       title = "Percent of Women in Poverty by Race and Ethnicity",
       caption = "Data Source: American Community Survey \n
       Adult women (18 and older), Fairfax County, Virginia, Census tracts, 2021", fill = "Percent") + 
  #caption = "A great phrase explaining my figure \n
  #Data Source: American Community Survey, 5-Year Estimates, Table S1702") + 
  scale_fill_distiller(palette = "Greens", direction = 1) +
  theme_void() + # Takes out x and y axis, axis labels 
  theme(legend.position = "bottom",
        text = element_text(size = 25),
        legend.key.width = unit(2, "cm")) +
  scale_color_manual(values = c("#00000000", "purple")) +
  guides(color = FALSE)
```

```{r}
tmap_mode("plot")  # static view - not interactive

tm_shape(w_df_maps) +
    tm_polygons(col = "pov_pct", 
                palette = "YlOrBr", 
                title = 'Percent',
                style = 'cont',
                textNA = "NA") +
    tm_facets(by = "race") +
    tm_layout(main.title = "Poverty Percent (Women) - 2021")

#tmap_save(filename="../docs/figures/women_pct_map.png", asp=0.75)
```


```{r}
pal <- brewer.pal(n=7,"Blues")[3:7]

tmap_mode("plot")  # static view - not interactive

tm_shape(w_df_maps) +
    tm_polygons(col = "pov_pct", 
                palette = "YlOrBr", 
                title = 'Percent',
                style = 'cont',
                #n=4,
                textNA = "NA") +
    tm_dots(col = "pov_cnt",
            palette = "Greens",
            style="fixed",
            breaks=c(0,25,50,100, max(w_df_maps$pov_cnt)),
            #n=4,
            size=0.07,
            shape = 21,
            border.col="black",
            border.lwd=0.3,
            title = "Count"
            ) +
    tm_facets(by = "race") +
    tm_layout(main.title = "Women in Poverty - 2021")

#tmap_save(filename="../docs/figures/womens_poverty_map.png", asp=0.7) #height=1080, width=1080)
```
